// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fpgmiomtgjvccipwiknw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwZ21pb210Z2p2Y2NpcHdpa253Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2NzAxNjMsImV4cCI6MjA1NDI0NjE2M30.S_WAqrvCTaT-VvRbtDY47lRhwBc7FjtHrRWs2J_E-FY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);